# Generated by Django 5.0 on 2024-01-24 07:37

import apps.template.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, unique=True)),
                ('subject', models.CharField(max_length=255, null=True)),
                ('type', models.CharField(choices=[('email', 'mr'), ('sms', 'mrs'), ('whatsapp', 'ms')], max_length=255, null=True)),
                ('message', models.TextField(null=True)),
                ('template_id', models.TextField(null=True)),
                ('parameters', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('smstype', models.CharField(choices=[('english', 'english'), ('hindi', 'hindi')], default=apps.template.utils.Smstype['english'], max_length=255)),
                ('whatsapptype', models.CharField(choices=[('text', 'text'), ('media', 'media')], default=apps.template.utils.Whatsapptype['text'], max_length=255)),
                ('whatsappmedia', models.ImageField(null=True, upload_to='whatsapp_media')),
                ('client_id', models.CharField(max_length=255, null=True)),
                ('created_by', models.CharField(max_length=255, null=True)),
                ('updated_by', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
