# Generated by Django 5.0 on 2024-01-24 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='whatsappmedia',
            field=models.ImageField(null=True, upload_to='media/whatsapp_media'),
        ),
    ]
