# Generated by Django 3.2.11 on 2023-07-10 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='communication',
            name='value',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
