# Generated by Django 5.0 on 2024-01-25 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calls', '0001_initial'),
        ('leads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='calls',
            name='lead_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='leads.leads'),
        ),
        migrations.AddField(
            model_name='calls',
            name='lead_status_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.stage'),
        ),
        migrations.AddField(
            model_name='timeslots',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
