# Generated by Django 5.0 on 2024-01-25 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='generalsettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_key', models.CharField(max_length=255, null=True, unique=True)),
                ('meta_value', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('client_id', models.CharField(max_length=255, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TellyCommSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('My-Telly', 'My-Telly'), ('My-Operator', 'My-Operator')], max_length=255)),
                ('phones', models.CharField(max_length=255, null=True, unique=True)),
                ('client_id', models.CharField(max_length=255, null=True)),
                ('auth_token', models.CharField(max_length=255, null=True)),
                ('outgoing_call', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255)),
                ('outgoing_call_name', models.CharField(blank=True, max_length=255, null=True)),
                ('outgoing_call_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('ivr_token', models.CharField(max_length=255, null=True)),
                ('company_id', models.CharField(max_length=255, null=True)),
                ('secret_token', models.CharField(max_length=255, null=True)),
                ('public_ivr_id', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
