# Generated by Django 3.2.11 on 2023-07-14 06:31

from django.db import migrations, models
import leads.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationFB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communication_id', models.BigIntegerField(blank=True, null=True)),
                ('communication_name', models.CharField(max_length=255, null=True)),
                ('fbpage_id', models.CharField(max_length=255, null=True)),
                ('fbpage_name', models.CharField(max_length=255, null=True)),
                ('fbform_id', models.CharField(max_length=255, null=True)),
                ('fbform_name', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.BigIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default=leads.utils.Status['inactive'], max_length=255)),
                ('client_id', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductFB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.BigIntegerField(blank=True, null=True)),
                ('product_name', models.CharField(max_length=255, null=True)),
                ('fbpage_id', models.CharField(max_length=255, null=True)),
                ('fbpage_name', models.CharField(max_length=255, null=True)),
                ('fbform_id', models.CharField(max_length=255, null=True)),
                ('fbform_name', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.BigIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default=leads.utils.Status['inactive'], max_length=255)),
                ('client_id', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionsFB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.CharField(max_length=255, null=True)),
                ('page_name', models.CharField(max_length=255, null=True)),
                ('fbform_id', models.CharField(max_length=255, null=True)),
                ('fbform_name', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.BigIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.BigIntegerField(blank=True, null=True)),
                ('access_token', models.CharField(max_length=255, null=True)),
                ('client_id', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
