# Generated by Django 3.2.6 on 2023-12-14 06:28

from django.db import migrations, models
import leads.utils


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelecallerFB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telecaller_id', models.BigIntegerField(blank=True, null=True)),
                ('telecaller_name', models.CharField(max_length=255, null=True)),
                ('fbpage_id', models.CharField(max_length=255, null=True)),
                ('fbpage_name', models.CharField(max_length=255, null=True)),
                ('fbform_id', models.CharField(max_length=255, null=True)),
                ('fbform_name', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.BigIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default=leads.utils.Status['inactive'], max_length=255)),
                ('client_id', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
